# Generated by Django 4.1.3 on 2022-11-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
